server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: my-picture-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_picture
    username: root
    password: 123456